language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository

script:
    - ./gradlew clean assembleDebug -PdisablePreDex --console=plain

cache:
  directories:
    - $HOME/.gradle/wrapper/